# Generated by Django 5.1.2 on 2024-11-25 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='fin',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='inicio',
        ),
    ]
