# Generated by Django 5.1.2 on 2024-11-25 09:12

import calendario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0002_remove_evento_fin_remove_evento_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fecha',
            field=models.DateField(validators=[calendario.models.validar_fecha]),
        ),
    ]
