# Generated by Django 5.1.2 on 2024-11-25 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0004_tipoevento_evento_tipos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='tipos',
        ),
    ]
