# Generated by Django 5.1.2 on 2024-11-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0005_remove_evento_tipos'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='tipos',
            field=models.ManyToManyField(to='calendario.tipoevento'),
        ),
    ]
