# Generated by Django 5.1.2 on 2024-11-28 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0006_evento_tipos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='tipos',
        ),
    ]
