# Generated by Django 5.1.2 on 2024-11-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0007_remove_evento_tipos'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='tipos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
